language: python

notifications:
    email: false

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

addons:
  apt:
    packages:
    # - sox
    - libsndfile1

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
#    - deps='pip atlas numpy scipy sphinx nose six future pep8 matplotlib decorator'
    - deps='pip numpy scipy'
    - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps
    - source activate test-environment
    - pip install -U pip
    - pip install python-coveralls
    - pip install pytest-faulthandler
    - pip install pytest-cov
#    - pip install numpydoc

install:
    - pip install -e .[tests]

#before_script:
#    - pep8 mir_eval evaluators tests

script:
#    - nosetests -v --with-coverage --cover-package=mir_eval
#    - python setup.py build_sphinx
#    - python setup.py egg_info -b.dev sdist --formats gztar
     - py.test

after_success:
    - coveralls
